APP_NAME = "WhereMyBus"
SCHEME = "App"

default_platform(:ios)

platform :ios do
    desc "인증서 가져오기"
    lane :sync do |options|
        match(
            type: "development",
            git_url: ENV["MATCH_URL"],
            keychain_password: ENV["MATCH_PASSWORD"],
            app_identifier: [
                "com.Pepsi-Club.WhereMyBus",
                "com.Pepsi-Club.WhereMyBus.Widget"
            ],
            readonly: true
        )
        match(
            type: "appstore",
            git_url: ENV["MATCH_URL"],
            keychain_password: ENV["MATCH_PASSWORD"],
            app_identifier: [
                "com.Pepsi-Club.WhereMyBus",
                "com.Pepsi-Club.WhereMyBus.Widget"
            ],
            readonly: true
        )
    end
    
    desc "local Push to TestFlight"
    lane :tf_local do |options|
        match(
            type: "appstore",
            app_identifier: [
                "com.Pepsi-Club.WhereMyBus",
                "com.Pepsi-Club.WhereMyBus.Widget"
            ],
            readonly: true
        )
        
        app_store_connect_api_key(
            key_id: ENV['APP_STORE_KEY_ID'],
            issuer_id: ENV['APP_STORE_ISSUER_ID'],
            key_content: ENV['APP_STORE_PRIVATE_KEY']
        )
        
        build_app(
            clean: true,
            workspace: "#{APP_NAME}.xcworkspace",
            scheme: "#{SCHEME}",
            export_method: "app-store",
        )
        
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end
    
    desc "Remote Push to TestFlight"
    lane :tf_remote do |options|
        create_keychain(
            name: ENV["KEYCHAIN_NAME"],
            password: ENV["KEYCHAIN_PASSWORD"],
            timeout: 1800,
            default_keychain: true,
            unlock: true,
            lock_when_sleeps: false
        )
                 
        app_store_connect_api_key(
            key_id: ENV['APP_STORE_KEY_ID'],
            issuer_id: ENV['APP_STORE_ISSUER_ID'],
            key_content: ENV['APP_STORE_PRIVATE_KEY'],
            is_key_content_base64: true,
            in_house: false
        )
        
        match(
            type: "development",
            keychain_name: ENV["KEYCHAIN_NAME"],
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            app_identifier: [
                "com.Pepsi-Club.WhereMyBus",
                "com.Pepsi-Club.WhereMyBus.Widget"
            ],
            readonly: true
        )
        
        match(
            type: "appstore",
            keychain_name: ENV["KEYCHAIN_NAME"],
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            app_identifier: [+
                "com.Pepsi-Club.WhereMyBus",
                "com.Pepsi-Club.WhereMyBus.Widget"
            ],
            readonly: true
        )
        
        build_app(
            workspace: "#{APP_NAME}.xcworkspace",
            scheme: "#{SCHEME}",
            export_method: "app-store"
        )
        
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end
end
