default_platform(:ios)

platform :ios do
  desc "Download Ignored"
  lane :getig do |options|
    Dir.chdir("../") do
      github_access_token = sh("git config --global user.password")
      sh("make download-privates token=#{github_access_token}")
    end
  end

  desc "Set Project"
  lane :setpj do |options|
    Dir.chdir("../") do
      sh("tuist clean")
      sh("tuist fetch")
      sh("tuist generate")
      match(
 	type: "development",
	git_url: ENV["MATCH_URL"],
        app_identifier:[
	  "com.Pepsi-Club.BusComing", 
	  "com.Pepsi-Club.BusComing.NotificationExtension" 
	],
        readonly: true
      )
    end
  end
end
